DROP TABLE video.VIDEO_CHANNEL;
DROP TABLE video.VIDEO_EVENT;
DROP TABLE video.VIDEO_HIGHLIGHT;
DROP TABLE video.VIDEO_HIT_UCC;
DROP TABLE video.VIDEO_VOD;
DROP TABLE video.UFLIX_PACKAGE;
DROP TABLE video.VIDEO_AUTO_COMPLETE;
DROP TABLE video.UFLIX_SERIES;
DROP TABLE video.UFLIX_TVG_AUTO_COMPLETE;
DROP TABLE video.UFLIX_MOBILE_AUTO_COMPLETE;
DROP TABLE video.DRAMA_MGMT;
DROP TABLE video.DRAMA_DATA;
DROP TABLE video.UFLIX_THEME;

  CREATE TABLE video.VIDEO_CHANNEL (
  SERVICE_ID VARCHAR(5) DEFAULT NULL,
  SERVICE_NAME VARCHAR(50) DEFAULT NULL,
  SERVICE_ENG_NAME VARCHAR(50) DEFAULT NULL,
  CHANNEL_NO VARCHAR(5) DEFAULT NULL,
  PROGRAM_ID VARCHAR(20) DEFAULT NULL,
  PROGRAM_NAME VARCHAR(100) DEFAULT NULL,
  THM_IMG_URL VARCHAR(300) DEFAULT NULL,
  THM_IMG_FILE_NAME VARCHAR(300) DEFAULT NULL,
  RATING CHAR(2) DEFAULT NULL,
  BROAD_TIME VARCHAR(10) DEFAULT NULL,
  DAY CHAR(3) DEFAULT NULL,
  OVERSEER_NAME VARCHAR(50) DEFAULT NULL,
  ACTOR VARCHAR(100) DEFAULT NULL,
  P_NAME VARCHAR(50) DEFAULT NULL,
  GENRE1 VARCHAR(20) DEFAULT NULL,
  GENRE2 VARCHAR(20) DEFAULT NULL,
  GENRE3 VARCHAR(20) DEFAULT NULL,
  SERIES_NO VARCHAR(5) DEFAULT NULL,
  SUB_NAME VARCHAR(100) DEFAULT NULL,
  BROAD_DATE VARCHAR(10) DEFAULT NULL,
  LOCAL_AREA VARCHAR(30) DEFAULT NULL,
  AV_RESOLUTION CHAR(2) DEFAULT NULL,
  Caption_Flag CHAR(1) DEFAULT NULL,
  Dvs_Flag CHAR(1) DEFAULT NULL,
  IS_51_CH CHAR(1) DEFAULT NULL,
  FILTERING_CODE CHAR(1) DEFAULT NULL,
  CHNL_KEYWORD VARCHAR(50) DEFAULT NULL,
  CHNL_ICON_URL VARCHAR(100) DEFAULT NULL,
  CHNL_ICON_FILE_NAME VARCHAR(100) DEFAULT NULL,
  PROGRAM_NAME_CHOSUNG VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY  (SERVICE_ID, PROGRAM_ID)
);

CREATE TABLE video.VIDEO_EVENT (
RESULT_TYPE VARCHAR(5) DEFAULT NULL,
SVC_TYPE CHAR(4) DEFAULT NULL,
REG_NO VARCHAR(15) DEFAULT NULL,
TITLE VARCHAR(50) DEFAULT NULL,
BANNER_URL VARCHAR(100) DEFAULT NULL,
START_DT CHAR(12) DEFAULT NULL,
END_DT CHAR(12) DEFAULT NULL,
PRIZE VARCHAR(100) DEFAULT NULL,
ANNOUNCE_YN CHAR(1) DEFAULT NULL,
EV_TYPE CHAR(3) DEFAULT NULL,
IS_NEW CHAR(1) DEFAULT NULL,
EV_STATUS CHAR(1) DEFAULT NULL,
KEYWORD VARCHAR(100) DEFAULT NULL,
OS_TYPE VARCHAR(3) DEFAULT NULL, 
MODEL VARCHAR(4000) DEFAULT NULL,
PRIMARY KEY  (REG_NO)
);

CREATE TABLE video.VIDEO_HIGHLIGHT (
RESULT_TYPE CHAR(5) DEFAULT NULL, 
SVC_TYPE CHAR(4) DEFAULT NULL,
CAT_ID CHAR(10) DEFAULT NULL,
CAT_NAME VARCHAR(100) DEFAULT NULL,
CONTENTS_ID CHAR(10) DEFAULT NULL,
CONTENTS_TYPE CHAR(1) DEFAULT NULL,
CONTENTS_NAME VARCHAR(100) DEFAULT NULL,
CONTENTS_INFO VARCHAR(255) DEFAULT NULL,
IMG_URL VARCHAR(255) DEFAULT NULL,
DURATION CHAR(8) DEFAULT NULL,
HIT_CNT VARCHAR(15) DEFAULT NULL,
H_ALBUM_ID VARCHAR(50) DEFAULT NULL,
H_CATEGORY_ID VARCHAR(50) DEFAULT NULL,
START_TIME CHAR(8) DEFAULT NULL,
END_TIME CHAR(8) DEFAULT NULL,
H_CONTENT_NAME VARCHAR(100) DEFAULT NULL,
H_SERIES_DESC  VARCHAR(50) DEFAULT NULL,
H_SERIES_NO VARCHAR(20) DEFAULT NULL,
H_SPONSOR_NAME VARCHAR(30) DEFAULT NULL,
H_STILL_IMG VARCHAR(255) DEFAULT NULL,
REG_DATE VARCHAR(14) DEFAULT NULL,
CONTENTS_NAME_CHOSUNG VARCHAR(100) DEFAULT NULL,
PRIMARY KEY  (CAT_ID, CONTENTS_ID)
);
  
CREATE TABLE video.VIDEO_HIT_UCC (
RESULT_TYPE VARCHAR(5) DEFAULT NULL, 
SVC_TYPE CHAR(4) DEFAULT NULL,
CAT_ID VARCHAR(10) DEFAULT NULL,
CAT_NAME VARCHAR(100) DEFAULT NULL,
CONTENTS_ID VARCHAR(10) DEFAULT NULL,
CONTENTS_TYPE CHAR(1) DEFAULT NULL,
CONTENTS_NAME VARCHAR(100) DEFAULT NULL,
CONTENTS_INFO VARCHAR(255) DEFAULT NULL,
CONTENTS_URL VARCHAR(512) DEFAULT NULL,
IMG_URL_HDTV VARCHAR(255) DEFAULT NULL,
IMG_URL_IPTV VARCHAR(255) DEFAULT NULL,
DURATION CHAR(8) DEFAULT NULL,
HIT_CNT VARCHAR(15) DEFAULT NULL, 
SITE_ID VARCHAR(10) DEFAULT NULL,  
SITE_NAME VARCHAR(50) DEFAULT NULL,
SITE_URL VARCHAR(100) DEFAULT NULL,
SITE_ICON_HDTV VARCHAR(255) DEFAULT NULL,
SITE_ICON_IPTV VARCHAR(255) DEFAULT NULL,
REG_DATE CHAR(14) DEFAULT NULL,
CONTENTS_NAME_CHOSUNG VARCHAR(100) DEFAULT NULL,
PRIMARY KEY  (CAT_ID, CONTENTS_ID)
  );  

#UPDATE시 사용INDEX 필드 [RESULT_TYPE,CAT_GB,CAT_ID,ALBUM_ID]
CREATE TABLE video.VIDEO_VOD (
  RESULT_TYPE VARCHAR(5) DEFAULT NULL,  
  CAT_GB CHAR(3) DEFAULT NULL,
  CAT_ID CHAR(5) DEFAULT NULL,       
  CAT_NAME VARCHAR(100) DEFAULT NULL,
  ALBUM_ID VARCHAR(20) DEFAULT NULL,
  ALBUM_NAME VARCHAR(100) DEFAULT NULL,
  IMG_URL VARCHAR(300) DEFAULT NULL,
  IMG_FILE_NAME VARCHAR(300) DEFAULT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  TYPE VARCHAR(5) DEFAULT NULL,   
  FLASH_YN CHAR(1) DEFAULT NULL,
  APPL_ID VARCHAR(40) DEFAULT NULL, 
  SERVICE_GB CHAR(3) DEFAULT NULL,
  APPL_URL VARCHAR(500) DEFAULT NULL,
  CREATE_DATE VARCHAR(14) DEFAULT NULL,
  UPDATE_DATE VARCHAR(8) DEFAULT NULL,
  IMG_TYPE CHAR(3) DEFAULT NULL,
  PRICE VARCHAR(15) DEFAULT NULL,
  PR_INFO CHAR(2) DEFAULT NULL,
  RUNTIME CHAR(4) DEFAULT NULL,
  IS_51_CH CHAR(1) DEFAULT NULL,
  IS_HOT CHAR(1) DEFAULT NULL,
  IS_CAPTION CHAR(1) DEFAULT NULL,
  IS_HD CHAR(1) DEFAULT NULL,
  CLOSE_YN CHAR(1) DEFAULT NULL,
  3D_YN CHAR(1) DEFAULT NULL,
  FILTER_GB CHAR(1) DEFAULT NULL,
  ACTOR VARCHAR(1000) DEFAULT NULL,
  OVERSEER_NAME VARCHAR(50) DEFAULT NULL,
  CONTS_SUBNAME VARCHAR(100) DEFAULT NULL,
  GENRE1 VARCHAR(20) DEFAULT NULL,
  GENRE2 VARCHAR(20) DEFAULT NULL,
  GENRE3 VARCHAR(20) DEFAULT NULL,
  SERIES_NO VARCHAR(30) DEFAULT NULL,
  PT CHAR(2) DEFAULT NULL,
  DES VARCHAR(1024) DEFAULT NULL,
  PRICE_2 VARCHAR(10) DEFAULT NULL,
  BROAD_DATE VARCHAR(20) DEFAULT NULL,
  STARRING_ACTOR VARCHAR(100) DEFAULT NULL,
  VOICE_ACTOR VARCHAR(100) DEFAULT NULL,
  BROADCASTER VARCHAR(50) DEFAULT NULL,
  RELEASE_DATE VARCHAR(8) DEFAULT NULL,
  IS_FH CHAR(1) DEFAULT NULL,
  SER_CAT_ID CHAR(5) DEFAULT NULL,
  MULTI_MAPPING_FLAG CHAR(1) DEFAULT NULL,
  POSTER_FILE_URL VARCHAR(300) DEFAULT NULL,
  POSTER_FILE_NAME_10 VARCHAR(300) DEFAULT NULL,
  POSTER_FILE_NAME_30 VARCHAR(300) DEFAULT NULL,
  KEYWORD_DESC VARCHAR(4096) DEFAULT NULL,
  TITLE_ENG VARCHAR(200) DEFAULT NULL,
  DIRECTOR_ENG VARCHAR(50) DEFAULT NULL,
  PLAYER_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME VARCHAR(100) DEFAULT NULL,
  TITLE_ORIGIN VARCHAR(200) DEFAULT NULL,
  WRITER_ORIGIN VARCHAR(200) DEFAULT NULL,
  PUBLIC_CNT VARCHAR(15) DEFAULT NULL,
  POINT_WATCHA CHAR(5) DEFAULT NULL,
  GENRE_UXTEN VARCHAR(20) DEFAULT NULL,
  RETENTION_YN CHAR(1) DEFAULT NULL,
  KEYWORD VARCHAR(1024) DEFAULT NULL,
  TITLE VARCHAR(200) DEFAULT NULL,
  CAST_NAME_MAX VARCHAR(750) DEFAULT NULL,
  CAST_NAME_MAX_ENG VARCHAR(750) DEFAULT NULL,
  ACT_DISP_MAX VARCHAR(1000) DEFAULT NULL,
  ACT_DISP_MAX_ENG VARCHAR(1000) DEFAULT NULL,
  POINT_ORDER VARCHAR(3) DEFAULT NULL,
  ALBUM_NO VARCHAR(30) DEFAULT NULL,
  STILL_IMG_NAME VARCHAR(300) DEFAULT NULL,
  CP_PROPERTY VARCHAR(10) DEFAULT NULL,
  CP_PROPERTY_UFX VARCHAR(10) DEFAULT NULL,
  THEME_YN CHAR(1) DEFAULT NULL,
  SECTION VARCHAR(10) DEFAULT NULL,
  KOFIC_SUPPORTING_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_EXTRA_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_SYNOPSIS TEXT DEFAULT NULL,
  KOFIC_KEYWORD VARCHAR(1000) DEFAULT NULL,
  KOFIC_FILM_STUDIO VARCHAR(500) DEFAULT NULL,
  KOFIC_FILM_DISTRIBUTOR VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_NATION VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_YEAR VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_SALE VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_AUDIENCE VARCHAR(100) DEFAULT NULL,
  CAT_NAME_CHOSUNG  TEXT DEFAULT NULL,
  ALBUM_NAME_CHOSUNG  TEXT DEFAULT NULL,
  ACTOR_CHOSUNG TEXT DEFAULT NULL,
  OVERSEER_NAME_CHOSUNG TEXT DEFAULT NULL,
  STARRING_ACTOR_CHOSUNG TEXT DEFAULT NULL,
  VOICE_ACTOR_CHOSUNG TEXT DEFAULT NULL,
  CAST_NAME_CHOSUNG TEXT DEFAULT NULL,
  KEYWORD_CHOSUNG TEXT DEFAULT NULL,
  TITLE_CHOSUNG TEXT DEFAULT NULL,
  CAST_NAME_MAX_CHOSUNG TEXT DEFAULT NULL,
  ACT_DISP_MAX_CHOSUNG TEXT DEFAULT NULL,
  PRIMARY KEY  (RESULT_TYPE,CAT_GB,CAT_ID,ALBUM_ID)
  );

#UPDATE시 사용INDEX 필드 [RESULT_TYPE,CAT_GB,CAT_ID,ALBUM_ID]
CREATE TABLE video.UFLIX_PACKAGE (
  RESULT_TYPE VARCHAR(10) DEFAULT NULL,  
  CAT_GB CHAR(3) DEFAULT NULL,
  CAT_ID CHAR(5) DEFAULT NULL,       
  CAT_NAME VARCHAR(100) DEFAULT NULL,
  ALBUM_ID VARCHAR(20) DEFAULT NULL,
  ALBUM_NAME VARCHAR(100) DEFAULT NULL,
  IMG_URL VARCHAR(300) DEFAULT NULL,
  IMG_FILE_NAME VARCHAR(300) DEFAULT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  TYPE VARCHAR(5) DEFAULT NULL,   
  FLASH_YN CHAR(1) DEFAULT NULL,
  APPL_ID VARCHAR(40) DEFAULT NULL, 
  SERVICE_GB CHAR(3) DEFAULT NULL,
  APPL_URL VARCHAR(500) DEFAULT NULL,
  CREATE_DATE VARCHAR(14) DEFAULT NULL,
  UPDATE_DATE VARCHAR(8) DEFAULT NULL,
  IMG_TYPE CHAR(3) DEFAULT NULL,
  PRICE VARCHAR(15) DEFAULT NULL,
  PR_INFO CHAR(2) DEFAULT NULL,
  RUNTIME CHAR(4) DEFAULT NULL,
  IS_51_CH CHAR(1) DEFAULT NULL,
  IS_HOT CHAR(1) DEFAULT NULL,
  IS_CAPTION CHAR(1) DEFAULT NULL,
  IS_HD CHAR(1) DEFAULT NULL,
  CLOSE_YN CHAR(1) DEFAULT NULL,
  3D_YN CHAR(1) DEFAULT NULL,
  FILTER_GB CHAR(1) DEFAULT NULL,
  ACTOR VARCHAR(1000) DEFAULT NULL,
  OVERSEER_NAME VARCHAR(50) DEFAULT NULL,
  CONTS_SUBNAME VARCHAR(100) DEFAULT NULL,
  GENRE1 VARCHAR(20) DEFAULT NULL,
  GENRE2 VARCHAR(20) DEFAULT NULL,
  GENRE3 VARCHAR(20) DEFAULT NULL,
  SERIES_NO VARCHAR(30) DEFAULT NULL,
  PT CHAR(2) DEFAULT NULL,
  DES VARCHAR(1024) DEFAULT NULL,
  PRICE_2 VARCHAR(10) DEFAULT NULL,
  BROAD_DATE VARCHAR(20) DEFAULT NULL,
  STARRING_ACTOR VARCHAR(100) DEFAULT NULL,
  VOICE_ACTOR VARCHAR(100) DEFAULT NULL,
  BROADCASTER VARCHAR(50) DEFAULT NULL,
  RELEASE_DATE VARCHAR(8) DEFAULT NULL,
  IS_FH CHAR(1) DEFAULT NULL,
  SER_CAT_ID CHAR(5) DEFAULT NULL,
  MULTI_MAPPING_FLAG CHAR(1) DEFAULT NULL,
  POSTER_FILE_URL VARCHAR(300) DEFAULT NULL,
  POSTER_FILE_NAME_10 VARCHAR(300) DEFAULT NULL,
  POSTER_FILE_NAME_30 VARCHAR(300) DEFAULT NULL,
  KEYWORD_DESC VARCHAR(4096) DEFAULT NULL,
  TITLE_ENG VARCHAR(200) DEFAULT NULL,
  DIRECTOR_ENG VARCHAR(50) DEFAULT NULL,
  PLAYER_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME VARCHAR(100) DEFAULT NULL,
  TITLE_ORIGIN VARCHAR(200) DEFAULT NULL,
  WRITER_ORIGIN VARCHAR(200) DEFAULT NULL,
  PUBLIC_CNT VARCHAR(15) DEFAULT NULL,
  POINT_WATCHA CHAR(5) DEFAULT NULL,
  GENRE_UXTEN VARCHAR(20) DEFAULT NULL,
  RETENTION_YN CHAR(1) DEFAULT NULL,
  KEYWORD VARCHAR(1024) DEFAULT NULL,
  TITLE VARCHAR(200) DEFAULT NULL,
  CAST_NAME_MAX VARCHAR(750) DEFAULT NULL,
  CAST_NAME_MAX_ENG VARCHAR(750) DEFAULT NULL,
  ACT_DISP_MAX VARCHAR(1000) DEFAULT NULL,
  ACT_DISP_MAX_ENG VARCHAR(1000) DEFAULT NULL,
  POINT_ORDER VARCHAR(3) DEFAULT NULL,
  ALBUM_NO VARCHAR(30) DEFAULT NULL,
  STILL_IMG_NAME VARCHAR(300) DEFAULT NULL,
  CP_PROPERTY VARCHAR(10) DEFAULT NULL,
  CP_PROPERTY_UFX VARCHAR(10) DEFAULT NULL,
  THEME_YN CHAR(1) DEFAULT NULL,
  KOFIC_SUPPORTING_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_EXTRA_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_SYNOPSIS TEXT DEFAULT NULL,
  KOFIC_KEYWORD VARCHAR(1000) DEFAULT NULL,
  KOFIC_FILM_STUDIO VARCHAR(500) DEFAULT NULL,
  KOFIC_FILM_DISTRIBUTOR VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_NATION VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_YEAR VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_SALE VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_AUDIENCE VARCHAR(100) DEFAULT NULL,
  CAT_NAME_CHOSUNG TEXT DEFAULT NULL,
  ALBUM_NAME_CHOSUNG  TEXT DEFAULT NULL,
  ACTOR_CHOSUNG  TEXT DEFAULT NULL,
  OVERSEER_NAME_CHOSUNG  TEXT DEFAULT NULL,
  STARRING_ACTOR_CHOSUNG  TEXT DEFAULT NULL,
  VOICE_ACTOR_CHOSUNG  TEXT DEFAULT NULL,
  CAST_NAME_CHOSUNG  TEXT DEFAULT NULL,
  KEYWORD_CHOSUNG  TEXT DEFAULT NULL,
  CAST_NAME_MAX_CHOSUNG  TEXT DEFAULT NULL,
  ACT_DISP_MAX_CHOSUNG  TEXT DEFAULT NULL,
  PRIMARY KEY  (RESULT_TYPE,CAT_GB,CAT_ID,ALBUM_ID)
  );
  
  #UPDATE시 사용INDEX 필드 [RESULT_TYPE, CAT_GB, CAT_ID, ID]
  CREATE TABLE video.UFLIX_SERIES (
  RESULT_TYPE VARCHAR(10) DEFAULT NULL,  
  CAT_GB CHAR(3) DEFAULT NULL,
  ID CHAR(20) DEFAULT NULL,       
  NAME VARCHAR(100) DEFAULT NULL,
  CAT_ID VARCHAR(20) DEFAULT NULL,
  IMG_URL VARCHAR(300) DEFAULT NULL,
  IMG_FILE_NAME VARCHAR(300) DEFAULT NULL,
  IMG_TYPE VARCHAR(5) DEFAULT NULL,   
  PRICE VARCHAR(15) DEFAULT NULL,
  PR_INFO CHAR(2) DEFAULT NULL,
  RUNTIME CHAR(4) DEFAULT NULL,
  IS_51_CH CHAR(1) DEFAULT NULL,
  IS_HOT CHAR(1) DEFAULT NULL,
  IS_CAPTION CHAR(1) DEFAULT NULL,
  IS_HD CHAR(1) DEFAULT NULL,
  CLOSE_YN CHAR(1) DEFAULT NULL,
  3D_YN CHAR(1) DEFAULT NULL,
  SERVICE_GB CHAR(3) DEFAULT NULL,
  FILTER_GB CHAR(1) DEFAULT NULL,
  SUMMARY VARCHAR(1024) DEFAULT NULL,
  ACTOR VARCHAR(1000) DEFAULT NULL,
  OVERSEER_NAME VARCHAR(50) DEFAULT NULL,
  CONTS_SUBNAME VARCHAR(100) DEFAULT NULL,
  GENRE1 VARCHAR(20) DEFAULT NULL,
  GENRE2 VARCHAR(20) DEFAULT NULL,
  GENRE3 VARCHAR(20) DEFAULT NULL,
  SERIES_NO VARCHAR(30) DEFAULT NULL,
  PT CHAR(2) DEFAULT NULL,
  DES VARCHAR(1024) DEFAULT NULL,
  PRICE_2 VARCHAR(10) DEFAULT NULL,
  BROAD_DATE VARCHAR(20) DEFAULT NULL,
  STARRING_ACTOR VARCHAR(100) DEFAULT NULL,
  VOICE_ACTOR VARCHAR(100) DEFAULT NULL,
  BROADCASTER VARCHAR(50) DEFAULT NULL,
  RELEASE_DATE VARCHAR(8) DEFAULT NULL,
  IS_FH CHAR(1) DEFAULT NULL,
  MULTI_MAPPING_FLAG CHAR(1) DEFAULT NULL,
  KEYWORD_DESC VARCHAR(4096) DEFAULT NULL,
  TITLE_ENG VARCHAR(200) DEFAULT NULL,
  DIRECTOR_ENG VARCHAR(50) DEFAULT NULL,
  PLAYER_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME_ENG VARCHAR(100) DEFAULT NULL,
  CAST_NAME VARCHAR(100) DEFAULT NULL,
  TITLE_ORIGIN VARCHAR(200) DEFAULT NULL,
  WRITER_ORIGIN VARCHAR(200) DEFAULT NULL,
  PUBLIC_CNT VARCHAR(15) DEFAULT NULL,
  POINT_WATCHA CHAR(5) DEFAULT NULL,
  GENRE_UXTEN VARCHAR(20) DEFAULT NULL,
  RETENTION_YN CHAR(1) DEFAULT NULL,
  KEYWORD VARCHAR(1024) DEFAULT NULL,
  TITLE VARCHAR(200) DEFAULT NULL,
  CAST_NAME_MAX VARCHAR(750) DEFAULT NULL,
  CAST_NAME_MAX_ENG VARCHAR(750) DEFAULT NULL,
  ACT_DISP_MAX VARCHAR(1000) DEFAULT NULL,
  ACT_DISP_MAX_ENG VARCHAR(1000) DEFAULT NULL,
  POINT_ORDER VARCHAR(3) DEFAULT NULL,
  ALBUM_NO VARCHAR(30) DEFAULT NULL,
  STILL_IMG_NAME VARCHAR(300) DEFAULT NULL,
  CP_PROPERTY VARCHAR(10) DEFAULT NULL,
  CP_PROPERTY_UFX VARCHAR(10) DEFAULT NULL,
  THEME_YN CHAR(1) DEFAULT NULL,
  KOFIC_SUPPORTING_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_EXTRA_ACTOR VARCHAR(1000) DEFAULT NULL,
  KOFIC_SYNOPSIS TEXT DEFAULT NULL,
  KOFIC_KEYWORD VARCHAR(1000) DEFAULT NULL,
  KOFIC_FILM_STUDIO VARCHAR(500) DEFAULT NULL,
  KOFIC_FILM_DISTRIBUTOR VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_NATION VARCHAR(100) DEFAULT NULL,
  KOFIC_MAKE_YEAR VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_SALE VARCHAR(100) DEFAULT NULL,
  KOFIC_SUM_AUDIENCE VARCHAR(100) DEFAULT NULL,
  NAME_CHOSUNG VARCHAR(100) DEFAULT NULL,
  ACTOR_CHOSUNG  VARCHAR(500) DEFAULT NULL,
  STARRING_ACTOR_CHOSUNG  VARCHAR(100) DEFAULT NULL,
  VOICE_ACTOR_CHOSUNG  VARCHAR(100) DEFAULT NULL,
  CAST_NAME_CHOSUNG  VARCHAR(100) DEFAULT NULL,
  KEYWORD_CHOSUNG  VARCHAR(1024) DEFAULT NULL,
  PRIMARY KEY (RESULT_TYPE, CAT_GB, CAT_ID, ID)
  );
  
  CREATE TABLE video.VIDEO_AUTO_COMPLETE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  KEYWORD VARCHAR(750) DEFAULT NULL,
  CNT INT DEFAULT 1,
  SEARCH_CNT INT DEFAULT 0,
  IS_CAT_NAME CHAR(1) DEFAULT 'N',
  IS_ALBUM_NAME CHAR(1) DEFAULT 'N',
  IS_ACTOR CHAR(1) DEFAULT 'N',
  IS_OVERSEER_NAME CHAR(1) DEFAULT 'N',
  IS_STARRING_ACTOR CHAR(1) DEFAULT 'N',
  IS_KEYWORD CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX_ENG CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX_ENG CHAR(1) DEFAULT 'N',
  KEYWORD_CHOSUNG VARCHAR(750) DEFAULT NULL,
  PRIMARY KEY (ID)
  );
  
  CREATE TABLE video.UFLIX_TVG_AUTO_COMPLETE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  KEYWORD VARCHAR(750) DEFAULT NULL,
  CNT INT DEFAULT 1,
  SEARCH_CNT INT DEFAULT 0,
  IS_CAT_NAME CHAR(1) DEFAULT 'N',
  IS_ALBUM_NAME CHAR(1) DEFAULT 'N',
  IS_ACTOR CHAR(1) DEFAULT 'N',
  IS_OVERSEER_NAME CHAR(1) DEFAULT 'N',
  IS_STARRING_ACTOR CHAR(1) DEFAULT 'N',
  IS_KEYWORD CHAR(1) DEFAULT 'N',
  IS_TITLE_ENG CHAR(1) DEFAULT 'N',
  IS_DIRECTOR_ENG CHAR(1) DEFAULT 'N',
  IS_PLAYER_ENG CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_ENG CHAR(1) DEFAULT 'N',
  IS_CAST_NAME CHAR(1) DEFAULT 'N',
  IS_TITLE_ORIGIN CHAR(1) DEFAULT 'N',
  IS_WRITER_ORIGIN CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX_ENG CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX_ENG CHAR(1) DEFAULT 'N',
  KEYWORD_CHOSUNG VARCHAR(750) DEFAULT NULL,
  PRIMARY KEY (ID)
  );
  
  CREATE TABLE video.UFLIX_MOBILE_AUTO_COMPLETE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  KEYWORD VARCHAR(750) DEFAULT NULL,
  CNT INT DEFAULT 1,
  SEARCH_CNT INT DEFAULT 0,
  IS_CAT_NAME CHAR(1) DEFAULT 'N',
  IS_ALBUM_NAME CHAR(1) DEFAULT 'N',
  IS_ACTOR CHAR(1) DEFAULT 'N',
  IS_OVERSEER_NAME CHAR(1) DEFAULT 'N',
  IS_STARRING_ACTOR CHAR(1) DEFAULT 'N',
  IS_KEYWORD CHAR(1) DEFAULT 'N',
  IS_TITLE_ENG CHAR(1) DEFAULT 'N',
  IS_DIRECTOR_ENG CHAR(1) DEFAULT 'N',
  IS_PLAYER_ENG CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_ENG CHAR(1) DEFAULT 'N',
  IS_CAST_NAME CHAR(1) DEFAULT 'N',
  IS_TITLE_ORIGIN CHAR(1) DEFAULT 'N',
  IS_WRITER_ORIGIN CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX CHAR(1) DEFAULT 'N',
  IS_CAST_NAME_MAX_ENG CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX CHAR(1) DEFAULT 'N',
  IS_ACT_DISP_MAX_ENG CHAR(1) DEFAULT 'N',
  KEYWORD_CHOSUNG VARCHAR(750) DEFAULT NULL,
  PRIMARY KEY (ID)
  );
  
  CREATE TABLE video.DRAMA_MGMT (
  COLLECTION_ID VARCHAR(32) NOT NULL,
  TERM_ID VARCHAR(64) NOT NULL,
  REL_TERM_ID VARCHAR(64) NOT NULL,
  IS_INSERT CHAR(1) NOT NULL,
  PRIMARY KEY (COLLECTION_ID,TERM_ID,REL_TERM_ID)
  );

  
  CREATE TABLE video.DRAMA_DATA (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  COLLECTION VARCHAR(32) NOT NULL,
  TERM VARCHAR(64) NOT NULL,
  REL_TERM VARCHAR(650) NOT NULL,
  PRIMARY KEY (ID)
  );


  CREATE TABLE video.UFLIX_THEME (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  THEME_ID VARCHAR(100) DEFAULT NULL,
  THEME_NM_M VARCHAR(100) DEFAULT NULL,
  THEME_NM_T VARCHAR(100) DEFAULT NULL,
  THEME_NM_P VARCHAR(100) DEFAULT NULL,
  THEME_IMG_M VARCHAR(255) DEFAULT NULL,
  THEME_IMG_T VARCHAR(255) DEFAULT NULL,
  THEME_IMG_P VARCHAR(255) DEFAULT NULL,
  KEYWORD VARCHAR(500) DEFAULT NULL,
  CONTENT_NM VARCHAR(100) DEFAULT NULL,
  ACTOR VARCHAR(100) DEFAULT NULL,
  DIRECTOR VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID)
  );

  #################### init 종료 ####
  
  DROP TABLE video.AUTO_COMPLETE_FIELD;
  DROP TABLE video.AUTO_COMPLETE_TYPE;
  
  CREATE TABLE video.AUTO_COMPLETE_FIELD (
  ID INT NOT NULL AUTO_INCREMENT,
  COLLECTION_NAME VARCHAR(50) NOT NULL,
  FIELD_ID VARCHAR(50) NOT NULL,
  FIELD_NAME VARCHAR(50) DEFAULT NULL,
  WEIGHT VARCHAR (50) NOT NULL,
  PRIMARY KEY (ID)
  );
  
  CREATE TABLE video.AUTO_COMPLETE_TYPE (
  ID INT NOT NULL AUTO_INCREMENT,
  COLLECTION_NAME VARCHAR(50) NOT NULL,
  TYPE CHAR(3) NOT NULL,
  TYPE_DESC VARCHAR(50) DEFAULT NULL,
  WEIGHT VARCHAR (50) NOT NULL,
  PRIMARY KEY (ID)
  );
  
  
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'CAT_NAME', '카테고리명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'ALBUM_NAME', '앨범 제목', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'ACTOR', '출연진', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'OVERSEER_NAME', '감독', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'STARRING_ACTOR', '주연', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'KEYWORD', '키워드-TAG', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'CAST_NAME_MAX', '등장인물 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'CAST_NAME_MAX_ENG', '등장인물 50인 - 영문', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'ACT_DISP_MAX', '등장인물 배역명 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'ACT_DISP_MAX_ENG', '등장인물 배역명 50인 -영문', '100');
 
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'CAT_NAME', '카테고리명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'ALBUM_NAME', '앨범 제목', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'ACTOR', '출연진', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'OVERSEER_NAME', '감독', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'STARRING_ACTOR', '주연', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'KEYWORD', '키워드-TAG', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'TITLE_ENG', '영화제목(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'DIRECTOR_ENG', '감독(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'PLAYER_ENG', '배우(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'CAST_NAME_ENG', '등장인물명(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'CAST_NAME', '등장인물명(한글)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'TITLE_ORIGIN', '원작명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'WRITER_ORIGIN', '원작자명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'CAST_NAME_MAX', '등장인물 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'CAST_NAME_MAX_ENG', '등장인물 50인 - 영문', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'ACT_DISP_MAX', '등장인물 배역명 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'ACT_DISP_MAX_ENG', '등장인물 배역명 50인 -영문', '100');


INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'CAT_NAME', '카테고리명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'ALBUM_NAME', '앨범 제목', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'ACTOR', '출연진', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'OVERSEER_NAME', '감독', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'STARRING_ACTOR', '주연', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'KEYWORD', '키워드-TAG', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'TITLE_ENG', '영화제목(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'DIRECTOR_ENG', '감독(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'PLAYER_ENG', '배우(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'CAST_NAME_ENG', '등장인물명(영문)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'CAST_NAME', '등장인물명(한글)', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'TITLE_ORIGIN', '원작명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'WRITER_ORIGIN', '원작자명', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'CAST_NAME_MAX', '등장인물 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'CAST_NAME_MAX_ENG', '등장인물 50인 - 영문', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'ACT_DISP_MAX', '등장인물 배역명 50인 - 한글', '100');
INSERT INTO `video`.`AUTO_COMPLETE_FIELD`(`COLLECTION_NAME`, `FIELD_ID`, `FIELD_NAME`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'ACT_DISP_MAX_ENG', '등장인물 배역명 50인 -영문', '100');

INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'SCW', '검색빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'DFW', '출현빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('VIDEO_AUTO_COMPLETE', 'FDW', '필드 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'SCW', '검색빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'DFW', '출현빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_MOBILE_AUTO_COMPLETE', 'FDW', '필드 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'SCW', '검색빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'DFW', '출현빈도 가중치', '1');
INSERT INTO `video`.`AUTO_COMPLETE_TYPE` (`COLLECTION_NAME`, `TYPE`, `TYPE_DESC`, `WEIGHT`)VALUES('UFLIX_TVG_AUTO_COMPLETE', 'FDW', '필드 가중치', '1');


### 오타보정  DB
  DROP TABLE manage.UPLUS_SYNONYM;  

  CREATE TABLE manage.UPLUS_SYNONYM (
  REP_KEYWORD VARCHAR(250) NOT NULL,
  KEYWORD VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (REP_KEYWORD, KEYWORD)
  );
  
  ##샘플데이터
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('어벤져스', '어벤자스');
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('어벤져스', '어밴자스');
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('어벤져스', '어밴즈스');
  
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('무한도전', '무도');
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('무한도전', '무모한도전');
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('무한도전', '무하돈전');
  INSERT INTO `manage`.`UPLUS_SYNONYM` (`REP_KEYWORD`, `KEYWORD`) VALUES('무한도전', '무한도저');
  
  